// src/tarotCards.js

export const tarotCards = [
  // === MAJOR ARCANA (22 lá Đại Ẩn) ===
  { id: 1, name: "The Fool", nameVi: "Chàng Khờ", type: "major" },
  { id: 2, name: "The Magician", nameVi: "Nhà Ảo Thuật", type: "major" },
  { id: 3, name: "The High Priestess", nameVi: "Nữ Tư Tế", type: "major" },
  { id: 4, name: "The Empress", nameVi: "Nữ Hoàng", type: "major" },
  { id: 5, name: "The Emperor", nameVi: "Hoàng Đế", type: "major" },
  { id: 6, name: "The Hierophant", nameVi: "Thầy Tế", type: "major" },
  { id: 7, name: "The Lovers", nameVi: "Tình Nhân", type: "major" },
  { id: 8, name: "The Chariot", nameVi: "Cỗ Xe Chiến Thắng", type: "major" },
  { id: 9, name: "Strength", nameVi: "Sức Mạnh", type: "major" },
  { id: 10, name: "The Hermit", nameVi: "Ẩn Sĩ", type: "major" },
  { id: 11, name: "Wheel of Fortune", nameVi: "Vòng Quay May Mắn", type: "major" },
  { id: 12, name: "Justice", nameVi: "Công Lý", type: "major" },
  { id: 13, name: "The Hanged Man", nameVi: "Kẻ Treo Ngược", type: "major" },
  { id: 14, name: "Death", nameVi: "Cái Chết", type: "major" },
  { id: 15, name: "Temperance", nameVi: "Tiết Độ", type: "major" },
  { id: 16, name: "The Devil", nameVi: "Ác Quỷ", type: "major" },
  { id: 17, name: "The Tower", nameVi: "Tòa Tháp", type: "major" },
  { id: 18, name: "The Star", nameVi: "Ngôi Sao", type: "major" },
  { id: 19, name: "The Moon", nameVi: "Mặt Trăng", type: "major" },
  { id: 20, name: "The Sun", nameVi: "Mặt Trời", type: "major" },
  { id: 21, name: "Judgement", nameVi: "Phán Xét", type: "major" },
  { id: 22, name: "The World", nameVi: "Thế Giới", type: "major" },

  // === WANDS ===
  { id: 23, name: "Ace of Wands", nameVi: "Át Gậy", type: "wands" },
  { id: 24, name: "Two of Wands", nameVi: "Hai Gậy", type: "wands" },
  { id: 25, name: "Three of Wands", nameVi: "Ba Gậy", type: "wands" },
  { id: 26, name: "Four of Wands", nameVi: "Bốn Gậy", type: "wands" },
  { id: 27, name: "Five of Wands", nameVi: "Năm Gậy", type: "wands" },
  { id: 28, name: "Six of Wands", nameVi: "Sáu Gậy", type: "wands" },
  { id: 29, name: "Seven of Wands", nameVi: "Bảy Gậy", type: "wands" },
  { id: 30, name: "Eight of Wands", nameVi: "Tám Gậy", type: "wands" },
  { id: 31, name: "Nine of Wands", nameVi: "Chín Gậy", type: "wands" },
  { id: 32, name: "Ten of Wands", nameVi: "Mười Gậy", type: "wands" },
  { id: 33, name: "Page of Wands", nameVi: "Tiểu Đồng Gậy", type: "wands" },
  { id: 34, name: "Knight of Wands", nameVi: "Hiệp Sĩ Gậy", type: "wands" },
  { id: 35, name: "Queen of Wands", nameVi: "Hoàng Hậu Gậy", type: "wands" },
  { id: 36, name: "King of Wands", nameVi: "Vua Gậy", type: "wands" },

  // === CUPS ===
  { id: 37, name: "Ace of Cups", nameVi: "Át Cốc", type: "cups" },
  { id: 38, name: "Two of Cups", nameVi: "Hai Cốc", type: "cups" },
  { id: 39, name: "Three of Cups", nameVi: "Ba Cốc", type: "cups" },
  { id: 40, name: "Four of Cups", nameVi: "Bốn Cốc", type: "cups" },
  { id: 41, name: "Five of Cups", nameVi: "Năm Cốc", type: "cups" },
  { id: 42, name: "Six of Cups", nameVi: "Sáu Cốc", type: "cups" },
  { id: 43, name: "Seven of Cups", nameVi: "Bảy Cốc", type: "cups" },
  { id: 44, name: "Eight of Cups", nameVi: "Tám Cốc", type: "cups" },
  { id: 45, name: "Nine of Cups", nameVi: "Chín Cốc", type: "cups" },
  { id: 46, name: "Ten of Cups", nameVi: "Mười Cốc", type: "cups" },
  { id: 47, name: "Page of Cups", nameVi: "Tiểu Đồng Cốc", type: "cups" },
  { id: 48, name: "Knight of Cups", nameVi: "Hiệp Sĩ Cốc", type: "cups" },
  { id: 49, name: "Queen of Cups", nameVi: "Hoàng Hậu Cốc", type: "cups" },
  { id: 50, name: "King of Cups", nameVi: "Vua Cốc", type: "cups" },

  // === SWORDS ===
  { id: 51, name: "Ace of Swords", nameVi: "Át Kiếm", type: "swords" },
  { id: 52, name: "Two of Swords", nameVi: "Hai Kiếm", type: "swords" },
  { id: 53, name: "Three of Swords", nameVi: "Ba Kiếm", type: "swords" },
  { id: 54, name: "Four of Swords", nameVi: "Bốn Kiếm", type: "swords" },
  { id: 55, name: "Five of Swords", nameVi: "Năm Kiếm", type: "swords" },
  { id: 56, name: "Six of Swords", nameVi: "Sáu Kiếm", type: "swords" },
  { id: 57, name: "Seven of Swords", nameVi: "Bảy Kiếm", type: "swords" },
  { id: 58, name: "Eight of Swords", nameVi: "Tám Kiếm", type: "swords" },
  { id: 59, name: "Nine of Swords", nameVi: "Chín Kiếm", type: "swords" },
  { id: 60, name: "Ten of Swords", nameVi: "Mười Kiếm", type: "swords" },
  { id: 61, name: "Page of Swords", nameVi: "Tiểu Đồng Kiếm", type: "swords" },
  { id: 62, name: "Knight of Swords", nameVi: "Hiệp Sĩ Kiếm", type: "swords" },
  { id: 63, name: "Queen of Swords", nameVi: "Hoàng Hậu Kiếm", type: "swords" },
  { id: 64, name: "King of Swords", nameVi: "Vua Kiếm", type: "swords" },

  // === PENTACLES ===
  { id: 65, name: "Ace of Pentacles", nameVi: "Át Tiền", type: "pentacles" },
  { id: 66, name: "Two of Pentacles", nameVi: "Hai Tiền", type: "pentacles" },
  { id: 67, name: "Three of Pentacles", nameVi: "Ba Tiền", type: "pentacles" },
  { id: 68, name: "Four of Pentacles", nameVi: "Bốn Tiền", type: "pentacles" },
  { id: 69, name: "Five of Pentacles", nameVi: "Năm Tiền", type: "pentacles" },
  { id: 70, name: "Six of Pentacles", nameVi: "Sáu Tiền", type: "pentacles" },
  { id: 71, name: "Seven of Pentacles", nameVi: "Bảy Tiền", type: "pentacles" },
  { id: 72, name: "Eight of Pentacles", nameVi: "Tám Tiền", type: "pentacles" },
  { id: 73, name: "Nine of Pentacles", nameVi: "Chín Tiền", type: "pentacles" },
  { id: 74, name: "Ten of Pentacles", nameVi: "Mười Tiền", type: "pentacles" },
  { id: 75, name: "Page of Pentacles", nameVi: "Tiểu Đồng Tiền", type: "pentacles" },
  { id: 76, name: "Knight of Pentacles", nameVi: "Hiệp Sĩ Tiền", type: "pentacles" },
  { id: 77, name: "Queen of Pentacles", nameVi: "Hoàng Hậu Tiền", type: "pentacles" },
  { id: 78, name: "King of Pentacles", nameVi: "Vua Tiền", type: "pentacles" }
];